### ISSUE TITLE
Los botones del HUD no funcionan

### ISSUE THREAD

**Issue by Sounagix** [while-true-studio/GoblinSlayer#10]
Al apretar la tecla escape se activan los botones pero no están activos.

**Comment by starias** [comment]
Respecto a esto propongo la solución de que en el menú de pausa e, lugar de hacer click en un botón que sea con el mismo teclado; por ejemplo: Con la tecla **P**, se reanudará el juego y con otra tecla se saldrá a la pantalla del título, porque he estado tocándolo y no encuentro otra solución, no sé qué pasa que los botones no funcionan, da igual donde lo pongas, que no funciona.
