### ISSUE TITLE
El HUD no muestra los valores reales de vida y maná

### ISSUE THREAD

**Issue by Sounagix** [while-true-studio/GoblinSlayer#26]

**Comment by starias** [comment]
A qué te refieres con que no muestra los valores reales ?? Porque la barra ya sabes como la hicimos, que se hace más grande o pequeña en función del maná total y el restante y siempre ha estado funcionando bien.

**Comment by Sounagix** [comment]
![Unity_OhTgmHIXmO](https://user-images.githubusercontent.com/36236348/56147249-2ddb4500-5fa8-11e9-9086-c2b988fbaf7e.png)

**Comment by Sounagix** [comment]
En la barra no se ve que tenga Hp pero en el script se ve que aun tiene hp.

**Comment by starias** [comment]
Vale, pues dime en qué rama está pasando eso, en la del Hito2 ??

**Comment by Sounagix** [comment]
Sip pero yo acabo de subir una versión con el chaman teleportable (es la última rama que subí )

**Comment by Sounagix** [comment]
Crea una y llámala Hito2BugFixed que salga de chamanTeleporter así usamos esa rama para arreglar los bugs.

**Comment by starias** [comment]
He estado mirando lo del HUD pero parece funcionar correctamente, no sé por qué te daba fallo, seguiré mirando a ver si encuentro algo.

**Comment by starias** [comment]
Vale, ta encontré el fallo. El componente *scrollbar* es lo que va a determinar el tamaño de la barra en su parámetro *size*; este parámetro se mueve en valores entre 0 y 1, pero el problema está cuando el tamaño baja de 0.13 ya que es ahí cuando alcanza su tamaño "0", ya que si baja de dicho valor la barra deja de ser visible pero sigue bajando su tamaño hasta llegar a 0.

**Comment by starias** [comment]
![image](https://user-images.githubusercontent.com/47497948/56567177-9e8bee00-65b4-11e9-825b-c6ca35688a07.png)

Ahí se puede observar como el *size* está a 0 y que es lo que pasa con la barra.

**Comment by starias** [comment]
Ya he implementado una primera solución, pero aún sin subir, ya que no es definitiva, quiero buscar otra alternativa mejor que la que tengo.
