### ISSUE TITLE
Los atacantes en melee hacen daño a todos los enemigos

### ISSUE THREAD

**Issue by Sounagix** [while-true-studio/GoblinSlayer#5]
Cuando se ataca a un enemigo hace daño a todos los enemigos fuera del rango

**Comment by kyranet** [comment]
Esto está causado por el colisionador circular de los rangers. Hay que refactorizarlos para medir la distancia entre el player y su transform. ~~Ya posteriormente haremos linecast/raycast para la detección de paredes y suelos.~~

EDIT: Los colisionadores circulares no eran necesarios, simplemente habíamos olvidado quitarlos al refactorizar el sistema.

**Comment by kyranet** [comment]
Fixed in 4a2c135
