### ISSUE TITLE
Pause Mode

### ISSUE THREAD

**Issue by AnassCarreau** [while-true-studio/GoblinSlayer#7]
Al pausar el juego los personajes se siguen moviendo.

**Comment by starias** [comment]
Hay una posible solución a este problema

**Comment by kyranet** [comment]
Y... ¿cuál es?

**Comment by starias** [comment]
Time.timeScale controla la velocidad a la que va a fluir el juego, siedo Time.timeScale = 1f la velocidad normal, por lo que si la ponemos a 0 el juego se congela para el menú de pausa y cuando se reanude, se pondrá a 1, recuperando la velocidad normal.
